export const SETTLEMENT_TYPES = {
  FULL_RELEASE: 'FULL_RELEASE',
  PARTIAL_RELEASE: 'PARTIAL_RELEASE',
  FULL_REFUND: 'FULL_REFUND',
};

export const SETTLEMENT_TYPE_VALUES = Object.values(SETTLEMENT_TYPES);
